id: b4fb1fa962144ecc97d54043a0a4fcb4
initial_creation_type: ocr
source_metadata:
  volumes:
    e2fb80dbf56d4ab2acd18d129112feb5:
      base_file: v092.txt
      image_group_id: I1PD95938
      title: སྡེ་པ་ཐ་དད་པར་བྱེད་པ་དང་རྣམ་པར་བཤད་པ།
      total_pages: 1484
      volume_number: 93
